MENU:
    basic:
        key: basic
        name: 基本档案
        icon: jbda
        type: xpath
        content: "/html/body/div[1]/div[5]/div[1]/div[2]/div[1]/ul/li[2]/p[2]"
        index: 0
        action: click
        submenu:
            supplier:
                key: supplier
                name: 供应商档案
                type: xpath
                content: /html/body/div[1]/div[5]/div[1]/div[2]/div[2]/div[7]
                index: 0
                action: open
                open:
                    class: active
                submenu:
                    supplier_info:
                        key: supplier_info
                        name: 4.1供应商档案管理
                        type: xpath
                        content: /html/body/div[1]/div[5]/div[1]/div[2]/div[2]/div[8]/ul/li[1]
                        index: 0
                        action: click
                        submenu:
                            close:
                                key: close
                                name: 关闭
                                type: xpath
                                content: //a[@id="tab-1018-closeEl"]
                                index: -1
                                action: jsclick
                                iframe: welcomeFrame
                                wait_disappear:
                                    type: xpath
                                    content: //div[@class="fakeloader"]
                                wait:
                                    type: xpath
                                    content: //a[@id="tab-1018-closeEl"]

TEST:
    - login
    - basic.supplier.supplier_info.close
    - basic.supplier.supplier_info
