MENU:
    purchase:
        key: purchase
        name: 接单
        icon: menu-icon-24
        type: xpath
        content: "//span[@style='padding-left: 18px;' and text()='客户订货']/../../.."
        index: 0
        action: open
        open:
            class: is-opened
        submenu:
            purchaseorder:
                key: purchaseorder
                name: 客户订货
                type: xpath
                content: //span[text()='客户订货']/..
                index: -1
                action: click
                submenu:
                    toaudit:
                        key: toaudit
                        name: 待审核
                        type: xpath
                        content: //div[@class='el-tabs__item is-top' and text()='待审核']
                        index: -1
                        action: click
                        submenu:
                            add:
                                key: add
                                name: 添加
                                type: xpath
                                content: //button[@class='btn btn-primary' and text()='添加']
                                index: -1
                                action: click
                                submenu:
                                    save:
                                        key: save
                                        name: 保存
                                        type: xpath
                                        content: //button[@class='btn btn-primary' and text()='保存']
                                        index: -1
                                        action: moveToClick
                                        operation:
                                            -
                                                name: 订货门店
                                                type: xpath
                                                content: //div[@class='vue-treeselect__placeholder vue-treeselect-helper-zoom-effect-off' and text()='请选择订货门店']/parent::div//input[@class='vue-treeselect__input']
#                                                content:
#                                                    -
#                                                        type: xpath
#                                                        content: //div[contains(@class, 'el-table__body-wrapper') and text()='请选择订货门店']
#                                                        index: -1
#                                                    -
#                                                        type: xpath
#                                                        content: .//td[contains(@class, 'el-table_2_column_35')]//input[@class='el-input__inner']
#                                                        index: -2
                                                index: -1
                                                action: click
                                            -
                                                name: 展开订货门店
                                                type: xpath
                                                content: //div[@class='vue-treeselect__placeholder vue-treeselect-helper-zoom-effect-off' and text()='请选择订货门店']/ancestor::div[@class='vue-treeselect__control']/following-sibling::div[@class='vue-treeselect__menu-container']//div[@class='vue-treeselect__option-arrow-container']
                                                index: -2
                                                action: clickList
                                            -
                                                name: 选中订货门店
                                                type: xpath
                                                content: //div[@class='vue-treeselect__placeholder vue-treeselect-helper-zoom-effect-off' and text()='请选择订货门店']/ancestor::div[@class='vue-treeselect__control']/following-sibling::div[@class='vue-treeselect__menu-container']//div[@class='vue-treeselect__list-item vue-treeselect__indent-level-1']//label
                                                index: -1
                                                action: click
                                            -
                                                name: 订货人
                                                type: xpath
                                                content: //input[@class='el-input__inner']
                                                index: 11
                                                value: pkgpath:utils.util.Util:randstr:10
                                                action: sendKeys
                                            -
                                                name: 订货人手机
                                                type: xpath
                                                content: //input[@class='el-input__inner']
                                                index: 9
                                                value: pkgpath:utils.util.Util:phone
                                                action: sendKeys
                                            -
                                                name: 备注
                                                type: xpath
                                                content: //input[@class='el-input__inner']
                                                index: 12
                                                value: pkgpath:utils.util.Util:randstr:7
                                                action: sendKeys
                                            -
                                                type: xpath
                                                content: //a[@class='jump-page-link' and text()='添加货品']
                                                index: -1
                                                action: click
                                            -
                                                name: 选择货品列表
                                                type: xpath
                                                content: //div[@id='dialog-customer-wrapper']//div[@class='el-table__header-wrapper']//label[@class='el-checkbox']
                                                index: 0
                                                javascript: setAttribute.role.checkbox
                                                action: moveToClick
                                            -
                                                type: xpath
                                                content: //button[@class='btn btn-info']
                                                index: -1
                                                action: click
                                            -
                                                name: 填写发货量(给列表填写数量)
                                                type: xpath
                                                content: ''
                                                index: -1
                                                value: pkgpath:utils.util.Util:randinterger:5
                                                action: sendListKeys
                                                contents:
                                                    -
                                                        type: xpath
                                                        content: //div[contains(@class, 'el-table__body-wrapper')]
                                                        index: 1
                                                    -
                                                        type: xpath
                                                        content: .//td[contains(@class, 'el-table_2_column_21 is-center ')]//input[@class='el-input__inner']
                                                        index: -2
                            edit:
                                key: edit
                                name: 编辑
                                type: xpath
                                content: //td[@class='el-table_1_column_7 is-center ']/div/a[@class='jump-page-link']
                                index: -1
                                action: click
                                submenu:
                                    save:
                                        key: save
                                        name: 保存
                                        type: xpath
                                        content: //button[@class='btn btn-info' and text()='保 存']
                                        index: -1
                                        action: click
                                        operation:
                                            -
                                                type: xpath
                                                content: //input[@class='form-control']
                                                index: 0
                                                value: pkgpath:utils.util.Util:randstr:6
                                                action: modifyKeys
                                            -
                                                type: xpath
                                                content: //input[@class='form-control']
                                                index: 1
                                                value: pkgpath:utils.util.Util:randstr:7
                                                action: modifyKeys
                            delete:
                                key: delete
                                name: 删除
                                type: xpath
                                content: //td[@class='el-table_1_column_7 is-center ']/div/a[@class='jump-page-link']
                                index: 1
                                action: click
                                submenu:
                                    confirm:
                                        key: confirm
                                        name: 确定
                                        type: xpath
                                        content: //button[@class='el-button el-button--default el-button--small el-button--primary ']
                                        index: -1
                                        action: click

TEST:
    - login
    - purchase.purchaseorder.toaudit.add.save
