MENU:
    pystest:
        key: pystest
        name: 打开pystest项目地址
        icon:
        type: xpath
        content: "//div[@class='result c-container new-pmd']//a[contains(text(), ' (sting) · GitHub')]"
        index: 0
        action: click
        submenu:
            open:
                key: open
                name: 打开github里pystest项目
                type: xpath
                content: //a[@href='/stingbo/pystest']
                index: 0
                action: click

TEST:
    - pystest.open
