MENU:
    testb:
        key: testb
        name: 基础档案
        icon: menu-icon-4
        type: xpath
        content: "//span[@style='padding-left: 18px;' and text()='销售价格']/../../.."
        index: 0
        action: open
        open:
            class: is-opened
        submenu:
            testb1:
                key: testb1
                name: 销售价格
                type: xpath
                content: //span[text()='销售价格']/..
                index: -1
                action: click
                submenu:
                    add:
                        key: add
                        name: 添加
                        type: xpath
                        content: //button[text()='添加']
                        index: -1
                        action: click
                        submenu:
                            save:
                                key: save
                                name: 保存
                                type: xpath
                                content: //button[@class='btn btn-primary' and text()='保存']
                                index: -1
                                action: click
                                operation:
                                    -
                                        name: 价格单名称
                                        type: name
                                        content: order_name
                                        index: -1
                                        value: pkgpath:utils.util.Util:randinterger
                                        #如何使用字符串和方法进行拼接
                                        action: sendKeys
                                    -
                                        name: 应用客户
                                        type: xpath
                                        content: //button[@class='el-button popover-btn el-button--default el-popover__reference']
                                        index: -1
                                        action: click
                                    -
                                        name: 选择客户分组
                                        type: xpath
                                        content: //span[@class='el-tree-node__expand-icon el-icon-caret-right']
                                        index: 0
                                        action: click
                                    -
                                        name: 选择客户
                                        type: xpath
                                        content: //span[@class='el-checkbox__inner']
                                        index: 3
                                        action: click
                                    -
                                        name: 确定
                                        type: xpath
                                        content: //button[@class='btn btn-info' and text()='确定']
                                        index: -1
                                        action: click
                                    -
                                        name: 添加货品
                                        type: xpath
                                        content: //a[@class='jump-page-link' and text()='添加货品']
                                        index: -1
                                        action: click
#                                    -
#                                        name: 选择分类
#                                        type: xpth
#                                        content: //input[@class='el-input__inner']
#                                        index: 10
#                                        action: click
#                                    -
#                                        name: 选择第二个分类
#                                        type: xpath
#                                        content: //span[@class='el-radio__inner' ]
#                                        index: 1
#                                        action: click
#                                    -
#                                        name: 查询
#                                        type: xpath
#                                        content: //button[@class='el-button el-button--default' ]
#                                        index: -1
#                                        action: click
                                    -
                                        name: 选择货品
                                        type: xpath
                                        #content: //span[@class='el-checkbox__inner']
                                        #单独定位定位不到，必须找上一级的div，联合着找(eg:delivery.yaml中)
                                        content: //div[@id='dialog-customer-wrapper']//div[@class='el-table__header-wrapper']//span[@class='el-checkbox__inner']
                                        index: 0
                                        javascript: setAttribute.role.checkbox
                                        action: moveToClick
                                    -
                                        name: 提交
                                        type: xpath
                                        content: //button[@class='btn btn-info' and text()='提交']
                                        index: -1
                                        action: click
                                    -
                                        name: 添加销售价格
                                        type: xpath
                                        content: ''
                                        index: -1
                                        value: pkgpath:utils.util.Util:randinterger:5
                                        action: sendListKeys
                                        contents:
                                            -
                                                type: xpath
                                                content: //div[(@class='el-table__body-wrapper is-scrolling-none')]
                                                index: -1
                                            -
                                                type: xpath
                                                content: .//td[@class='el-table_2_column_17 is-center ']//input[@class='el-input__inner']
                                                index: -2


TEST:
    - login #表示config.example.yaml里的loign配置
    - testb.testb1
