MENU:
    order_receiving:
        key: order_receiving
        name: 接单
        icon: menu-icon-24
        type: xpath
        content: "//span[@style='padding-left: 18px;' and text() = '客户订货']/../../.."
        index: 0
        action: open
        open:
            class: is-open
        submenu:
            customer_order:
                key: customer_order
                name: 客户订货
                type: xpath
                content: //span[text()='客户订货']/..
                index: -1
                action: click
                submenu:
                    toaudit:
                        key: toaudit
                        name: 待审核
                        type: xpath
                        content: //div[@class='el-tabs__item is-top' and text()='待审核']
                        index: -1
                        action: click
                        submenu:
                            alter:
                                key: alter
                                name: 修改
                                type: xpath
                                content: //div[@class='el-table__fixed-body-wrapper']//a[@class = 'jump-page-link' and text() ='修改']
#                                content: //td[@class='el-table_6_column_67 is-center  is-hidden']//a[@class = 'jump-page-link' and text() ='修改']
                                index: 0
                                action: click
                                submenu:
                                    save:
                                        key: save
                                        name: 修改保存
                                        type: xpath
                                        content: //button[@class='btn btn-primary' and text()='保存']
                                        index: -1
                                        action: click
                                        operation:
                                            -
                                                name: 修改订货人
                                                type: xpath
                                                content: //div[@class='table-header']//input[@placeholder='选填，限10字以内']
                                                index: -1
                                                value: pkgpath:utils.util.Util:randstr:7
                                                action: modifyKeys
                                            -
                                                name: 修改订货人手机
                                                type: xpath
                                                content: //div[@class='table-header']//input[@placeholder='请输入订货人手机号']
                                                index: -1
                                                value: pkgpath:utils.util.Util:phone
                                                action: modifyKeys


TEST:
    - login
    - order_receiving.customer_order.toaudit.alter.save
